package by.bsuir.labwork_2;

import by.bsuir.labwork_2.entity.Appliance;
import by.bsuir.labwork_2.entity.criteria.ApplianceCriteria;
import by.bsuir.labwork_2.service.ApplianceService;
import by.bsuir.labwork_2.service.ServiceFactory;
import by.bsuir.labwork_2.util.PrintApplianceInfo;

import java.util.Arrays;
import java.util.Comparator;

/**
 * This is project represent second lab work of web technologies course
 *
 * Generated by {@autor Daniil Kautunou}
 */

public class Main {

    public static void main(String[] args) {
        Appliance[] appliance;

        ServiceFactory factory = ServiceFactory.getInstance();
        ApplianceService service = factory.getApplianceService();

        /**
         * All teapots
         */
        ApplianceCriteria allTeapotsCriteria = new ApplianceCriteria("teapot");
        appliance = service.findByCriteria(allTeapotsCriteria);
        PrintApplianceInfo.printInfo(appliance);

        System.out.println("--------------------------------------------------------------------------------");

        /**
         * CHEAPEST APPLIANCE
         */
        ApplianceCriteria allAppliancesCriteria = new ApplianceCriteria();
        appliance = service.findByCriteria(allAppliancesCriteria);

        PrintApplianceInfo.printInfo(
                Arrays.stream(appliance)
                        .min(Comparator.comparing(Appliance::getCost))
                        .get()
        );
    }
}
